spring:
 application:
  name: test01

--- # Start

--- # change port
server:
 port: 8081


--- # Thymeleaf
spring:
 thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html

--- # mariadb
spring:
 datasource:
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://192.168.219.106:3306/atoz
  username: atoz
  password: atoz9897

mybatis:
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # MyBatis 표준 로거 설정

logging:
 level:
  root: info
  com.example.demo: debug  # 패키지 수준 로깅 (필요에 따라 조정)
  org.apache.ibatis: debug  # MyBatis SQL 로깅

--- #국제화
spring:
 messages:
  basename: messages/messages
  encoding: UTF-8

--- #정적페이지
spring:
 web:
  resources:
   static-locations: classpath:/static/

--- #mybatis
mybatis:
 mapper-locations: classpath:/mapper/**/*.xml