spring.application.name=test01

--- # Start

--- # change port
server:
 port: 8080

--- # Thymeleaf
spring:
 thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html

--- # mariadb
spring:
 datasource:
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3306/kkm
  username: kkm
  password: 12345

--- #jpa
spring:
 jpa:
  hibernate:
   ddl-auto: update
  show_sql : true
 #properties:
  #hibernate:
   #format_sql: true

--- #devTools
spring:
 devtools:
  restart:
   enabled: true    # 자동 리스타트 기능 활성화 (기본값: true)
  livereload:
   enabled: true    # 라이브 리로드 기능 활성화 (기본값: true)

--- #국제화
spring:
 messages:
  basename: messages/messages
  encoding: UTF-8

--- #정적페이지
spring:
 web:
  resources:
   static-locations: classpath:/static/

--- #mybatis
mybatis:
 mapper-locations: classpath:/mapper/**/*.xml